# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.15
    working_directory: ~/go/src/github.com/skybet/go-helpdesk
    steps:
      - checkout
      - run: go get golang.org/x/tools/cmd/cover github.com/mattn/goveralls github.com/ory/go-acc
      - run: go-acc -o coverage.txt github.com/skybet/go-helpdesk/wrapper github.com/skybet/go-helpdesk/server github.com/skybet/go-helpdesk/handlers
      - run: go test -v ./...
      - run: goveralls -service=circle-ci -coverprofile=coverage.txt -repotoken=$COVERALLS_REPO_TOKEN
      - setup_remote_docker
      - run: docker build -t adampointer83/go-helpdesk:$CIRCLE_SHA1 .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push adampointer83/go-helpdesk:$CIRCLE_SHA1
         
