# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/skybet/go-helpdesk
    steps:
      - checkout
      - run: go get golang.org/x/tools/cmd/cover github.com/mattn/goveralls github.com/ory/go-acc
      - run: go-acc -o coverage.txt ./...
      - run: go test -v ./...
      - run: goveralls -service=circle-ci -coverprofile=coverage.txt -repotoken=$COVERALLS_REPO_TOKEN
