// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"
import slack "github.com/nlopes/slack"

// SlackWrapper is an autogenerated mock type for the SlackWrapper type
type SlackWrapper struct {
	mock.Mock
}

// OpenDialog provides a mock function with given fields: triggerID, dialog
func (_m *SlackWrapper) OpenDialog(triggerID string, dialog slack.Dialog) error {
	ret := _m.Called(triggerID, dialog)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, slack.Dialog) error); ok {
		r0 = rf(triggerID, dialog)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendMessage provides a mock function with given fields: message, channel
func (_m *SlackWrapper) SendMessage(message string, channel string) {
	_m.Called(message, channel)
}
